language: haskell
env:
  - CABALVER=1.22
before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER 
  - export PATH=/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
  - cabal --version
  - travis_retry wget -q -O- https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -
  - travis_retry echo 'deb http://download.fpcomplete.com/ubuntu/precise stable main'|sudo tee /etc/apt/sources.list.d/fpco.list
  - travis_retry sudo apt-get update && sudo apt-get install stack -y
install:
  - stack setup
script:
  - stack test
